[package]
name = "hammer_fastx"
version = "0.1.0"
edition = "2021"

[dependencies]
bio = "1.2.0"
clap = { version = "4.5.7", features = ["derive"] }
csv = "1.3.0"
flate2 = "1.0.30"
indicatif = "0.17.8"
anyhow = "1.0.86"
rayon = "1.10.0"
crossbeam-channel = "0.5.13"
num_cpus = "1.16.0"
